@startuml

class User {
    + static final Map<String, User> map
    - static int count

    # int id
    + String name
    + int age
    # String username
    # String password

    + User(String name, int age, String username, String password)

    + int getId()
    + String getUsername()
    + boolean loginBool (String username, String password)
}

class Librarian {
    + Librarian(String name, int age, String username, String password)
    # void enableUser(Student student)
    # void disableUser(Student student)
}

class Student {
    + boolean enabled
    + Status status
    - final Date dateCreated

    + Student(String name, int age, String username, String password)
    + Student(String name, int age, String username, String password, Status status)
    - Student(Status status, Date dateCreated, String name, int age, String username, String password)


    + Date getDateCreated()
    + void browseBooks()
}

enum Status {
        FRESHMAN
        SOPHMORE
        JUNIOR
        SENIOR

        + static Status fromInteger(int n)
        + String toString()
}

class Borrowing {
    # int id
    + Book[] books
    + Student borrower
    + Date dateBorrowed
    + Date dateDue

    + Borrowing()

    + void update()
}

class Book {
    # int id
    + Stromg title
    + String details
    + String publisher

    + void add()
    + void update()
}

User <|-- Student
User <|-- Librarian
Student *-- Status
Student *-- Borrowing
Borrowing -- Librarian
Borrowing o-- Book
Librarian -- Student
Book -- Librarian

@enduml